#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

root_dir_path="$(realpath "$(dirname "$0")")" || exit
readonly root_dir_path
readonly local_ts_node="$root_dir_path/node_modules/.bin/ts-node"
readonly local_eslint="$root_dir_path/node_modules/.bin/eslint"

if [ ! -x "$local_ts_node" ]; then
	if ! command -v npm > '/dev/null'; then
		echo "$0: npm: missing program" >&2
		exit 48
	fi

	{ cd "$root_dir_path" && npm install; } || exit
fi

if [ -x "$local_eslint" ]; then
	find "$root_dir_path" -type f \( -wholename "$root_dir_path/src/*" -name '*.ts' \) -print0 |
			xargs -0 "$local_eslint" "$@"
fi &&
	"$local_ts_node" 'src/main.ts' "$@"
